
DROP TABLE BOARD;

CREATE TABLE BOARD (
  BBS_GB CHAR(2) NOT NULL ,
  SEQ NUMBER NOT NULL ,
  TITLE VARCHAR2(10),
  CONTS VARCHAR2(30),
  RECDATE DATE,
  CNT NUMBER,
  CONSTRAINT BOARD_PK PRIMARY KEY (BBS_GB, SEQ)
);

INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';
INSERT INTO BOARD SELECT 'AA', NVL(MAX(SEQ), 0) + 1, 'TEST', 'TEST', SYSDATE, 0 FROM BOARD WHERE BBS_GB='AA';

COMMIT;

SELECT * FROM BOARD;