-- 팀별 년간 경기가 열리는 개월 수
# select TEAM.TEAM_NAME, MONTHS_BETWEEN(MIN(SCHEDULE.SCHE_DATE), MAX(SCHEDULE.SCHE_DATE))
select TEAM.TEAM_NAME, ROUND(DATEDIFF(MAX(SCHEDULE.SCHE_DATE), MIN(SCHEDULE.SCHE_DATE))/30, 1)
from SCHEDULE join TEAM
  on SCHEDULE.HOMETEAM_ID=TEAM.TEAM_ID
group by TEAM.TEAM_NAME