-- 성이 홍씨이고 포지션이 수비수인 선수 정보

SELECT TEAM_ID, PLAYER_NAME, POSITION
FROM PLAYER
WHERE PLAYER_NAME LIKE '홍%'
AND POSITION = 'DF'
ORDER BY TEAM_ID, PLAYER_NAME;

-- SORT ORDER BY
---- TABLE ACCESS BY INDEX POWID:PLAYER
------ INDEX RANGE SCAN:PLAYER_IDX_POSITION

SELECT TEAM_ID, PLAYER_NAME, POSITION
FROM PLAYER
WHERE PLAYER_NAME LIKE '홍%'
AND RTRIM(POSITION) = 'DF'
ORDER BY TEAM_ID, PLAYER_NAME;

-- SORT ORDER BY
---- TABLE ACCESS BY INDEX ROWID:PLAYER
------ INDEX RANGE SCAN:PLAYER_IDX_PLAYER_NAME
