--  K  리그 선수 중 생년이 70년대인 선수 정보를 팀 코드, 선수명, 생년월일 순으로 조회하라.

-- CREATE INDEX PLAYER_IDX_BIRTH ON PLAYER_T(BIRTH_DATE);

SELECT TEAM_ID, PLAYER_NAME, TO_CHAR(BIRTH, 'YYYYMMDD')
FROM PLAYER_T
WHERE TO_CHAR(BIRTH, 'YYYYMMDD') BETWEEN 19700101 AND 19791231
ORDER BY TEAM_ID, PLAYER_NAME;

-- SORT ORDER BY
--   TABLE ACCESS FULL:PLAYER

SELECT TEAM_ID, PLAYER_NAME, BIRTH
FROM PLAYER_T
WHERE BIRTH BETWEEN TO_DATE('19700101','YYYYMMDD') AND
TO_DATE('19791231','YYYYMMDD')
ORDER BY TEAM_ID, PLAYER_NAME;

--sort (order by)
--PLAYER_T - TABLE ACCESS (full)