
-- K 리그 선수 중 닉네임이 있는 선수 정보를 팀 코드, 선수명, 닉네임 순으로 조회
CREATE INDEX PLAYER_IDX_NICKNAME ON PLAYER_T(NICKNAME);

SELECT TEAM_ID, PLAYER_NAME, NICKNAME
FROM PLAYER
WHERE NICKNAME IS NOT NULL
ORDER BY TEAM_ID, PLAYER_NAME;

-- SORT ORDER BY
--  TABLE ACCESS FULL:PLAYER

SELECT TEAM_ID, PLAYER_NAME, NICKNAME
FROM PLAYER_T
WHERE NICKNAME IS NOT NULL
ORDER BY TEAM_ID, PLAYER_NAME;

-- SORT ORDER BY
---- TABLE ACCESS BY INDEX ROWID:PLAYER
------ INDEX RANGE SCAN:PLAYER_IDX_NICKNAME

