-- 다음 SQL 문을 INDEX가 스캔 되도록 수정하라. 단, 필요한 INDEX는 모두 생성된 상태로 가정한다.
-- NOT OPERATOR TUNNING

SELECT TEAM_ID, PLAYER_NAME, POSITION
FROM PLAYER_T
WHERE POSITION <> 'DF'
ORDER BY TEAM_ID, PLAYER_NAME;

SELECT TEAM_ID, PLAYER_NAME, POSITION
FROM  PLAYER
WHERE POSITION < 'DF'
OR    POSITION > 'DF'
ORDER BY TEAM_ID, PLAYER_NAME;