-- 다음 SQL 문을 INDEX가 스캔 되도록 수정하라.
-- 단, 필요한 index는 모두 생성된 상태로 가정한다.
-- birth_date는 데이터 타입이 date 타입이다.

SELECT TEAM_ID, PLAYER_NAME, POSITION, BIRTH_DATE
FROM PLAYER_T
WHERE TO_CHAR(BIRTH_DATE,'YYYYMMDD') BETWEEN '19700101' AND '19791231'
ORDER BY TEAM_ID, PLAYER_NAME;

--

SELECT TEAM_ID, PLAYER_NAME, POSITION, BIRTH_DATE
FROM  PLAYER
WHERE BIRTH_DATE BETWEEN
TO_DATE('19700101','YYYYMMDD) AND TO_DATE('19791231','YYYYMMDD')
ORDER BY TEAM_ID, PLAYER_NAME;