# print 99 if null

select TEAM.TEAM_NAME, PLAYER.PLAYER_NAME, IF(PLAYER.BACK_NO=0, 99, PLAYER.BACK_NO), PLAYER.POSITION
from PLAYER NATURAL JOIN TEAM
where TEAM_ID='K02'

select TEAM.TEAM_NAME, PLAYER.PLAYER_NAME, NVL(PLAYER.BACK_NO, '99'), PLAYER.POSITION
from PLAYER NATURAL JOIN TEAM
where TEAM_ID='K02'